package world.player.skill.slayer

/**
 * An enum representing slayer masters and their tasks.
 */
enum class SlayerMaster(val combatLevel: Int = 0, val slayerLevel: Int = 9, val tasks: List<SlayerTaskData>) {
    TURAEL(tasks = listOf(
        SlayerTaskData(task = SlayerTask.BANSHEE, amount = 15..30, weight = 8),
        SlayerTaskData(task = SlayerTask.BAT, amount = 15..30, weight = 7),
        SlayerTaskData(task = SlayerTask.BEAR, amount = 10..20, weight = 7),
        SlayerTaskData(task = SlayerTask.BIRD, amount = 15..30, weight = 6),
        SlayerTaskData(task = SlayerTask.CAVE_BUG, amount = 10..30, weight = 8),
        SlayerTaskData(task = SlayerTask.CAVE_CRAWLER, amount = 15..30, weight = 8),
        SlayerTaskData(task = SlayerTask.CAVE_SLIME, amount = 10..20, weight = 8),
        SlayerTaskData(task = SlayerTask.COW, amount = 15..30, weight = 8),
        SlayerTaskData(task = SlayerTask.CRAWLING_HAND, amount = 15..30, weight = 8),
        SlayerTaskData(task = SlayerTask.DOG, amount = 15..30, weight = 7),
        SlayerTaskData(task = SlayerTask.DWARF, amount = 10..25, weight = 7),
        SlayerTaskData(task = SlayerTask.GHOST, amount = 15..30, weight = 7),
        SlayerTaskData(task = SlayerTask.GOBLIN, amount = 15..30, weight = 7),
        SlayerTaskData(task = SlayerTask.ICEFIEND, amount = 15..20, weight = 8),
        SlayerTaskData(task = SlayerTask.KALPHITE, amount = 15..30, weight = 6),
        SlayerTaskData(task = SlayerTask.LIZARD, amount = 15..30, weight = 8),
        SlayerTaskData(task = SlayerTask.MONKEY, amount = 15..30, weight = 6),
        SlayerTaskData(task = SlayerTask.RAT, amount = 15..30, weight = 7),
        SlayerTaskData(task = SlayerTask.SCORPION, amount = 15..30, weight = 7),
        SlayerTaskData(task = SlayerTask.SKELETON, amount = 15..30, weight = 7),
        SlayerTaskData(task = SlayerTask.SPIDER, amount = 15..30, weight = 6),
        SlayerTaskData(task = SlayerTask.WOLF, amount = 15..30, weight = 7),
        SlayerTaskData(task = SlayerTask.ZOMBIE, amount = 15..30, weight = 7)
    )),

    MAZCHNA(combatLevel = 20,
            tasks = listOf(
                SlayerTaskData(task = SlayerTask.BANSHEE, amount = 30..50, weight = 8),
                SlayerTaskData(task = SlayerTask.BAT, amount = 30..50, weight = 7),
                SlayerTaskData(task = SlayerTask.BEAR, amount = 30..50, weight = 6),
                SlayerTaskData(task = SlayerTask.CAVE_BUG, amount = 10..20, weight = 8),
                SlayerTaskData(task = SlayerTask.CAVE_CRAWLER, amount = 30..50, weight = 8),
                SlayerTaskData(task = SlayerTask.CAVE_SLIME, amount = 10..20, weight = 8),
                SlayerTaskData(task = SlayerTask.CRAWLING_HAND, amount = 30..50, weight = 8),
                SlayerTaskData(task = SlayerTask.DOG, amount = 30..50, weight = 7),
                SlayerTaskData(task = SlayerTask.GHOST, amount = 30..50, weight = 7),
                SlayerTaskData(task = SlayerTask.GHOUL, amount = 10..20, weight = 7),
                SlayerTaskData(task = SlayerTask.HILL_GIANT, amount = 30..50, weight = 7),
                SlayerTaskData(task = SlayerTask.HOBGOBLIN, amount = 30..50, weight = 7),
                SlayerTaskData(task = SlayerTask.ICE_WARRIOR, amount = 40..50, weight = 7),
                SlayerTaskData(task = SlayerTask.KALPHITE, amount = 30..50, weight = 6),
                SlayerTaskData(task = SlayerTask.KILLERWATT, amount = 30..50, weight = 6),
                SlayerTaskData(task = SlayerTask.LIZARD, amount = 30..50, weight = 8),
                SlayerTaskData(task = SlayerTask.MOGRE, amount = 30..50, weight = 8),
                SlayerTaskData(task = SlayerTask.PYREFIEND, amount = 30..50, weight = 8),
                SlayerTaskData(task = SlayerTask.ROCKSLUG, amount = 30..50, weight = 8),
                SlayerTaskData(task = SlayerTask.SCORPION, amount = 30..50, weight = 7),
                SlayerTaskData(task = SlayerTask.SHADE, amount = 30..70, weight = 8),
                SlayerTaskData(task = SlayerTask.SKELETON, amount = 30..50, weight = 7),
                SlayerTaskData(task = SlayerTask.WALL_BEAST, amount = 10..20, weight = 7),
                SlayerTaskData(task = SlayerTask.WOLF, amount = 30..50, weight = 7),
                SlayerTaskData(task = SlayerTask.ZOMBIE, amount = 30..50, weight = 7)
            )),

    VANNAKA(combatLevel = 40,
            tasks = listOf(
                SlayerTaskData(task = SlayerTask.ABERRANT_SPECTRE, amount = 40..90, weight = 8),
                SlayerTaskData(task = SlayerTask.BASILISK, amount = 40..90, weight = 8),
                SlayerTaskData(task = SlayerTask.BLOODVELD, amount = 40..90, weight = 8),
                SlayerTaskData(task = SlayerTask.COCKATRICE, amount = 40..90, weight = 8),
                SlayerTaskData(task = SlayerTask.ROCK_CRAB, amount = 40..90, weight = 8),
                SlayerTaskData(task = SlayerTask.DUST_DEVIL, amount = 40..90, weight = 8),
                SlayerTaskData(task = SlayerTask.HARPIE_BUG_SWARM, amount = 40..90, weight = 8),
                SlayerTaskData(task = SlayerTask.INFERNAL_MAGE, amount = 40..90, weight = 8),
                SlayerTaskData(task = SlayerTask.JELLY, amount = 40..90, weight = 8),
                SlayerTaskData(task = SlayerTask.OTHERWORLDLY_BEING, amount = 40..90, weight = 8),
                SlayerTaskData(task = SlayerTask.PYREFIEND, amount = 40..90, weight = 8),
                SlayerTaskData(task = SlayerTask.SHADE, amount = 40..90, weight = 8),
                SlayerTaskData(task = SlayerTask.SHADOW_WARRIOR, amount = 30..80, weight = 8),
                SlayerTaskData(task = SlayerTask.TUROTH, amount = 30..90, weight = 8),
                SlayerTaskData(task = SlayerTask.BLUE_DRAGON, amount = 40..90, weight = 7),
                SlayerTaskData(task = SlayerTask.DAGANNOTH, amount = 40..90, weight = 7),
                SlayerTaskData(task = SlayerTask.ELF, amount = 30..70, weight = 7),
                SlayerTaskData(task = SlayerTask.FEVER_SPIDER, amount = 30..90, weight = 7),
                SlayerTaskData(task = SlayerTask.FIRE_GIANT, amount = 40..90, weight = 7),
                SlayerTaskData(task = SlayerTask.GHOUL, amount = 10..40, weight = 7),
                SlayerTaskData(task = SlayerTask.HELLHOUND, amount = 30..60, weight = 7),
                SlayerTaskData(task = SlayerTask.HILL_GIANT, amount = 40..90, weight = 7),
                SlayerTaskData(task = SlayerTask.HOBGOBLIN, amount = 40..90, weight = 7),
                SlayerTaskData(task = SlayerTask.ICE_GIANT, amount = 30..80, weight = 7),
                SlayerTaskData(task = SlayerTask.ICE_WARRIOR, amount = 40..90, weight = 7),
                SlayerTaskData(task = SlayerTask.KALPHITE, amount = 40..90, weight = 7),
                SlayerTaskData(task = SlayerTask.KURASK, amount = 40..90, weight = 7),
                SlayerTaskData(task = SlayerTask.LESSER_DEMON, amount = 40..90, weight = 7),
                SlayerTaskData(task = SlayerTask.MOGRE, amount = 40..90, weight = 7),
                SlayerTaskData(task = SlayerTask.MOSS_GIANT, amount = 40..90, weight = 7),
                SlayerTaskData(task = SlayerTask.OGRE, amount = 40..90, weight = 7),
                SlayerTaskData(task = SlayerTask.TROLL, amount = 40..90, weight = 7),
                SlayerTaskData(task = SlayerTask.WEREWOLF, amount = 30..60, weight = 7),
                SlayerTaskData(task = SlayerTask.KURASK, amount = 40..90, weight = 7),
                SlayerTaskData(task = SlayerTask.CROCODILE, amount = 40..90, weight = 6),
                SlayerTaskData(task = SlayerTask.ABYSSAL_DEMON, amount = 40..90, weight = 5),
                SlayerTaskData(task = SlayerTask.GARGOYLE, amount = 40..90, weight = 5),
                SlayerTaskData(task = SlayerTask.NECHRYAEL, amount = 40..90, weight = 5)
            )),

    CHAELDAR(combatLevel = 70,
             tasks = listOf(
                 SlayerTaskData(task = SlayerTask.ABYSSAL_DEMON, amount = 70..130, weight = 12),
                 SlayerTaskData(task = SlayerTask.FIRE_GIANT, amount = 70..130, weight = 12),
                 SlayerTaskData(task = SlayerTask.KURASK, amount = 70..130, weight = 12),
                 SlayerTaskData(task = SlayerTask.NECHRYAEL, amount = 70..130, weight = 12),
                 SlayerTaskData(task = SlayerTask.DAGANNOTH, amount = 70..130, weight = 11),
                 SlayerTaskData(task = SlayerTask.GARGOYLE, amount = 70..130, weight = 11),
                 SlayerTaskData(task = SlayerTask.KALPHITE, amount = 70..130, weight = 11),
                 SlayerTaskData(task = SlayerTask.TROLL, amount = 70..130, weight = 11),
                 SlayerTaskData(task = SlayerTask.BLACK_DEMON, amount = 70..130, weight = 11),
                 SlayerTaskData(task = SlayerTask.JELLY, amount = 70..130, weight = 10),
                 SlayerTaskData(task = SlayerTask.TUROTH, amount = 70..130, weight = 10),
                 SlayerTaskData(task = SlayerTask.DUST_DEVIL, amount = 70..130, weight = 9),
                 SlayerTaskData(task = SlayerTask.GREATER_DEMON, amount = 70..130, weight = 9),
                 SlayerTaskData(task = SlayerTask.HELLHOUND, amount = 70..130, weight = 9),
                 SlayerTaskData(task = SlayerTask.LESSER_DEMON, amount = 70..130, weight = 9),
                 SlayerTaskData(task = SlayerTask.ABERRANT_SPECTRE, amount = 70..130, weight = 8),
                 SlayerTaskData(task = SlayerTask.BLOODVELD, amount = 70..130, weight = 8),
                 SlayerTaskData(task = SlayerTask.BLUE_DRAGON, amount = 70..130, weight = 8),
                 SlayerTaskData(task = SlayerTask.ROCK_CRAB, amount = 70..130, weight = 8),
                 SlayerTaskData(task = SlayerTask.ELF, amount = 70..130, weight = 8),
                 SlayerTaskData(task = SlayerTask.SHADOW_WARRIOR, amount = 70..130, weight = 8),
                 SlayerTaskData(task = SlayerTask.BASILISK, amount = 70..130, weight = 7),
                 SlayerTaskData(task = SlayerTask.FEVER_SPIDER, amount = 70..130, weight = 7),
                 SlayerTaskData(task = SlayerTask.ZYGOMITE, amount = 8..15, weight = 7),
                 SlayerTaskData(task = SlayerTask.SKELETAL_WYVERN, amount = 10..20, weight = 7)
             )),

    DURADEL(combatLevel = 100,
            slayerLevel = 50,
            tasks = listOf(
                SlayerTaskData(task = SlayerTask.ABYSSAL_DEMON, amount = 130..200, weight = 12),
                SlayerTaskData(task = SlayerTask.DARK_BEAST, amount = 10..20, weight = 11),
                SlayerTaskData(task = SlayerTask.HELLHOUND, amount = 130..200, weight = 10),
                SlayerTaskData(task = SlayerTask.BLACK_DRAGON, amount = 10..20, weight = 9),
                SlayerTaskData(task = SlayerTask.DAGANNOTH, amount = 130..199, weight = 9),
                SlayerTaskData(task = SlayerTask.GREATER_DEMON, amount = 130..200, weight = 9),
                SlayerTaskData(task = SlayerTask.KALPHITE, amount = 130..200, weight = 9),
                SlayerTaskData(task = SlayerTask.GREATER_DEMON, amount = 130..200, weight = 9),
                SlayerTaskData(task = SlayerTask.NECHRYAEL, amount = 130..200, weight = 9),
                SlayerTaskData(task = SlayerTask.BLACK_DEMON, amount = 130..200, weight = 8),
                SlayerTaskData(task = SlayerTask.BLOODVELD, amount = 130..200, weight = 8),
                SlayerTaskData(task = SlayerTask.GARGOYLE, amount = 130..200, weight = 8),
                SlayerTaskData(task = SlayerTask.RED_DRAGON, amount = 30..65, weight = 8),
                SlayerTaskData(task = SlayerTask.ABERRANT_SPECTRE, amount = 130..200, weight = 7),
                SlayerTaskData(task = SlayerTask.BASILISK, amount = 130..200, weight = 7),
                SlayerTaskData(task = SlayerTask.FIRE_GIANT, amount = 130..200, weight = 7),
                SlayerTaskData(task = SlayerTask.SKELETAL_WYVERN, amount = 20..40, weight = 7),
                SlayerTaskData(task = SlayerTask.STEEL_DRAGON, amount = 10..20, weight = 7),
                SlayerTaskData(task = SlayerTask.TROLL, amount = 130..200, weight = 6),
                SlayerTaskData(task = SlayerTask.DUST_DEVIL, amount = 130..200, weight = 5),
                SlayerTaskData(task = SlayerTask.IRON_DRAGON, amount = 40..60, weight = 5),
                SlayerTaskData(task = SlayerTask.BLUE_DRAGON, amount = 110..170, weight = 4),
                SlayerTaskData(task = SlayerTask.ELF, amount = 110..170, weight = 4),
                SlayerTaskData(task = SlayerTask.KURASK, amount = 130..200, weight = 4),
                SlayerTaskData(task = SlayerTask.ZYGOMITE, amount = 20..30, weight = 2)
            ))
}