package io.luna.game.model.mob.combat.attack;

import api.combat.magic.CombatSpellHandler;
import game.player.Sound;
import io.luna.game.model.LocalProjectile;
import io.luna.game.model.LocalSound;
import io.luna.game.model.def.CombatSpellDefinition;
import io.luna.game.model.mob.Mob;
import io.luna.game.model.mob.block.Animation;
import io.luna.game.model.mob.block.Graphic;
import io.luna.game.model.mob.combat.CombatSpell;
import io.luna.game.model.mob.combat.damage.CombatDamage;
import io.luna.game.model.mob.combat.damage.CombatDamageAction;
import io.luna.game.model.mob.combat.damage.CombatDamageType;
import io.luna.game.model.mob.interact.InteractionPolicy;
import io.luna.game.model.mob.interact.InteractionType;

import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.function.BiFunction;

/**
 * A {@link CombatAttack} implementation for magic attacks driven by a {@link CombatSpellDefinition}.
 * <p>
 * The primary hit for this attack is resolved as {@link CombatDamageType#MAGIC}. Any secondary hits produced by spell
 * effects, such as multi-target or area-of-effect behavior, are accumulated in {@link #damageList} and applied after
 * the primary hit resolves accurately.
 *
 * @param <T> The concrete {@link Mob} type performing the magic attack.
 * @author lare96
 */
public class MagicCombatAttack<T extends Mob> extends CombatAttack<T> {

    /**
     * Additional damage entries generated by spell-specific effects.
     * <p>
     * This list is usually populated by {@link CombatSpellHandler#effect(CombatSpell, MagicCombatAttack)} and then
     * drained by {@link #applyEffects()} after the primary hit lands.
     */
    protected final List<CombatDamage> damageList = new ArrayList<>();

    /**
     * The cast animation played by the attacker.
     */
    private final Animation cast;

    /**
     * The starting graphic displayed on the attacker, if any.
     */
    private final Graphic start;

    /**
     * Produces the projectile to launch for this spell, if any.
     */
    private final BiFunction<Mob, Mob, LocalProjectile> projectileFunction;

    /**
     * The ending graphic displayed on a successfully hit victim, if any.
     */
    private final Graphic end;

    /**
     * The sound played when the spell impacts successfully, if any.
     */
    private final Sound impactSound;

    /**
     * The spell definition used to resolve spell-specific secondary effects.
     */
    protected final CombatSpellDefinition spellEffect;

    /**
     * Creates a new {@link MagicCombatAttack} using explicit visual and effect data.
     *
     * @param attacker The mob casting the spell.
     * @param victim The target being attacked.
     * @param cast The cast animation to play.
     * @param start The starting graphic to display on the attacker, or {@code null} if none.
     * @param projectileFunction Produces the projectile to launch, or {@code null} if the spell has no projectile.
     * @param end The ending graphic to display on a successful impact, or {@code null} if none.
     * @param impactSound The sound to play on a successful impact, or {@code null} if none.
     * @param spellEffect The spell definition used to resolve spell-specific effects.
     * @param speed The attack delay, in ticks, applied after execution.
     */
    public MagicCombatAttack(T attacker, Mob victim, Animation cast, Graphic start,
                             BiFunction<Mob, Mob, LocalProjectile> projectileFunction, Graphic end, Sound impactSound,
                             CombatSpell spellEffect, int speed) {
        super(attacker, victim, new InteractionPolicy(InteractionType.LINE_OF_SIGHT, 10), speed);
        this.cast = cast;
        this.start = start;
        this.projectileFunction = projectileFunction;
        this.end = end;
        this.impactSound = impactSound;
        this.spellEffect = spellEffect.getDef();
    }

    /**
     * Creates a new {@link MagicCombatAttack} from a {@link CombatSpellDefinition}.
     *
     * @param attacker The mob casting the spell.
     * @param victim The target being attacked.
     * @param spell The spell definition to execute.
     * @param speed The attack delay, in ticks, applied after execution.
     */
    public MagicCombatAttack(T attacker, Mob victim, CombatSpellDefinition spell, int speed) {
        this(attacker, victim, spell.getCastAnimation(), spell.getStartGraphic(), spell.getProjectile(),
                spell.getEndGraphic(), spell.getEndSound(), spell.getSpell(), speed);
    }

    /**
     * Creates a new {@link MagicCombatAttack} from a {@link CombatSpell} wrapper.
     *
     * @param attacker The mob casting the spell.
     * @param victim The target being attacked.
     * @param spell The combat spell to execute.
     * @param speed The attack delay, in ticks, applied after execution.
     */
    public MagicCombatAttack(T attacker, Mob victim, CombatSpell spell, int speed) {
        this(attacker, victim, spell.getDef(), speed);
    }

    @Override
    public void attack() {
        attacker.animation(cast);
        if (start != null) {
            attacker.graphic(start);
        }
        launchProjectile();
    }

    @Override
    public CombatDamage calculateDamage(Mob other) {
        // Use spell effect max hit.
        return CombatDamage.computeAccuracy(attacker, other, CombatDamageType.MAGIC).
                computeDamage(spellEffect.getMaxHit());
    }

    @Override
    public void onProjectileLaunched() {
        if (projectileFunction != null) {
            LocalProjectile projectile = projectileFunction.apply(attacker, victim);
            projectile.display();
        }
    }

    @Override
    public void onProjectileReached() {
        if (nextDamage.getAmount().isPresent()) {
            // The hit landed successfully, so apply spell effects and successful impact visuals.
            applyEffects();
            if (end != null) {
                victim.graphic(end);
            }
            if (impactSound != null) {
                LocalSound.of(victim, impactSound).display();
            }
        } else {
            // The hit splashed, so play the standard splash effect.
            victim.graphic(new Graphic(85, 100));
            LocalSound.of(victim, Sound.MAGIC_SPLASH).display();
        }
        victim.submitAction(new CombatDamageAction(nextDamage, true));
    }

    /**
     * Intercepts an additional damage entry produced by a spell effect before it is queued.
     * <p>
     * Subclasses may override this to modify, replace, or suppress an individual secondary effect hit.
     *
     * @param damage The secondary effect damage being processed.
     * @return The final effect damage to apply, or {@code null} to skip this secondary effect entry.
     */
    public CombatDamage onEffect(CombatDamage damage) {
        return damage;
    }

    /**
     * Applies spell-specific secondary effects after a successful primary hit.
     * <p>
     * This delegates to {@link CombatSpellHandler} to resolve any special behavior associated with the active spell.
     * Those effects may append additional {@link CombatDamage} entries to {@link #damageList}.
     * <p>
     * Each queued secondary hit is passed through {@link #onEffect(CombatDamage)} and, if still present, submitted to
     * that hit's victim. If this spell defines an ending graphic, that graphic is also displayed on each affected victim.
     */
    private void applyEffects() {
        if (spellEffect != null) {
            CombatSpellHandler.INSTANCE.effect(spellEffect.getSpell(), this);

            Iterator<CombatDamage> it = damageList.iterator();
            while (it.hasNext()) {
                CombatDamage effectDamage = onEffect(it.next());
                it.remove();
                if (effectDamage == null) {
                    continue;
                }
                effectDamage.getVictim().submitAction(new CombatDamageAction(effectDamage, true));
                if (end != null) {
                    effectDamage.getVictim().graphic(end);
                }
            }
        }
    }

    /**
     * @return The additional effect damage entries.
     */
    public final List<CombatDamage> getDamageList() {
        return damageList;
    }

    /**
     * @return The current spell effect definition, or {@code null} if none is set.
     */
    public CombatSpellDefinition getSpellEffect() {
        return spellEffect;
    }
}