package world.player.skill.crafting

/**
 *
 *
 * @author lare96 <http://github.com/lare96>
 */
enum class HideArmor(val id: Int = 0, val level: Int = 0, val exp: Double = 0.0, val hides: Pair<Hide, Int>? = null) {
    LEATHER_GLOVES(id = 1059,
                   level = 1,
                   exp = 13.8,
                   hides = Pair(Hide.SOFT_LEATHER, 1)),
    LEATHER_BOOTS(id = 1061,
                  level = 7,
                  exp = 16.25,
                  hides = Pair(Hide.SOFT_LEATHER, 1)),
    LEATHER_COWL(id = 1167,
                 level = 9,
                 exp = 25.0,
                 hides = Pair(Hide.SOFT_LEATHER, 1)),
    LEATHER_VAMBRACES(id = 1063,
                      level = 11,
                      exp = 22.0,
                      hides = Pair(Hide.SOFT_LEATHER, 1)),
    LEATHER_BODY(id = 1129,
                 level = 14,
                 exp = 25.0,
                 hides = Pair(Hide.SOFT_LEATHER, 1)),
    LEATHER_CHAPS(id = 1095,
                  level = 18,
                  exp = 27.0,
                  hides = Pair(Hide.SOFT_LEATHER, 1)),
    HARD_LEATHER_BODY(id = 1131,
                      level = 28,
                      exp = 35.0,
                      hides = Pair(Hide.HARD_LEATHER, 1)),
    COIF(id = 1169,
         level = 38,
         exp = 37.0,
         hides = Pair(Hide.SOFT_LEATHER, 1)),
    STUDDED_BODY(id = 1133,
                 level = 41,
                 exp = 40.0),
    STUDDED_CHAPS(id = 1097,
                  level = 44,
                  exp = 42.0),
    SNAKESKIN_BOOTS(id = 6328,
                    level = 45,
                    exp = 30.0,
                    hides = Pair(Hide.SNAKESKIN, 6)),
    SNAKESKIN_BRACE(id = 6330,
                    level = 47,
                    exp = 35.0,
                    hides = Pair(Hide.SNAKESKIN, 8)),
    SNAKESKIN_BANDANA(id = 6326,
                      level = 48,
                      exp = 45.0,
                      hides = Pair(Hide.SNAKESKIN, 5)),
    SNAKESKIN_CHAPS(id = 6324,
                    level = 51,
                    exp = 50.0,
                    hides = Pair(Hide.SNAKESKIN, 12)),
    SNAKESKIN_BODY(id = 6322,
                   level = 53,
                   exp = 55.0,
                   hides = Pair(Hide.SNAKESKIN, 15)),
    GREEN_DHIDE_BODY,
    GREEN_DHIDE_CHAPS,
    GREEN_DHIDE_VAMBRACES,
    BLUE_DHIDE_BODY,
    BLUE_DHIDE_CHAPS,
    BLUE_DHIDE_VAMBRACES,
    RED_DHIDE_BODY,
    RED_DHIDE_CHAPS,
    RED_DHIDE_VAMBRACES,
    BLACK_DHIDE_BODY,
    BLACK_DHIDE_CHAPS,
    BLACK_DHIDE_VAMBRACES;

    companion object {
        val SNAKESKIN = listOf(SNAKESKIN_BANDANA, SNAKESKIN_BODY)
    }
}