package game.combat.spells

import api.combat.magic.CombatSpellHandler.immobilize
import api.combat.magic.CombatSpellHandler.spell
import api.combat.magic.CombatSpellHandler.weaken
import api.predef.*
import engine.controllers.Controllers.inMultiArea
import io.luna.game.model.area.Area
import io.luna.game.model.mob.Mob
import io.luna.game.model.mob.Player
import io.luna.game.model.mob.combat.CombatSpell
import io.luna.game.model.mob.combat.attack.MagicCombatAttack
import io.luna.game.model.mob.combat.damage.CombatDamage
import io.luna.util.RandomUtils
import io.luna.util.Rational
import kotlin.math.floor

/**
 * The chance for a smoke spell to apply poison.
 */
val SMOKE_SPELLS_POISON_CHANCE = Rational(1, 8)

/**
 * Iterates nearby viewable mobs of the same runtime type as the supplied victim, limited to a radius around
 * that victim.
 *
 * Only mobs other than the victim itself that are inside the radius and currently in a multi-combat area are passed
 * to {@code action}.
 *
 * @param victim The center mob used to determine radius, world, and runtime mob type.
 * @param radius The search radius around the victim.
 * @param action The action to perform for each matching nearby mob.
 */
inline fun <reified T : Mob> forRadiusMobs(victim: T, radius: Int, action: (Mob) -> Unit) {
    val area = Area.of(victim.position, radius)
    val viewable: Set<T> = world.locator.findViewable(victim.type, victim.position)
    for (mob in viewable) {
        if (mob != victim && area.contains(mob) && mob.inMultiArea()) {
            action(mob)
        }
    }
}

/**
 * Attempts to poison the primary victim of a smoke spell and any secondary victims reached by the spell's area effect.
 *
 * Poison is applied independently per victim using [SMOKE_SPELLS_POISON_CHANCE]. Whenever a secondary target is
 * affected, a corresponding damage entry is also queued onto the attack.
 *
 * @param victim The primary victim of the spell.
 * @param severity The poison severity to apply on a successful poison roll.
 * @param attack The active magic attack providing spell metadata and secondary-hit storage.
 */
fun poison(victim: Mob, severity: Int, attack: MagicCombatAttack<*>) {
    fun poison(mob: Mob) {
        if (RandomUtils.roll(SMOKE_SPELLS_POISON_CHANCE)) {
            mob.combat.poisonSeverity = severity
        }
    }
    poison(victim)
    if (attack.spellEffect.radius > 0 && attack.attacker.inMultiArea()) {
        forRadiusMobs(victim, attack.spellEffect.radius) {
            poison(it)
            attack.damageList += attack.calculateDamage(it)
        }
    }
}

/**
 * Heals the attacker for one quarter of the supplied damage amount and applies the same effect to any secondary
 * targets generated by the spell.
 *
 * The heal amount is calculated as `floor(damage * 0.25)`. If the resulting value is less than `1`, no healing is
 * applied for that hit.
 *
 * A player attacker is also notified that health was drained.
 *
 * @param attacker The mob receiving the healing effect.
 * @param damage The primary combat damage used to derive the initial heal amount.
 * @param attack The active magic attack providing spell metadata and secondary-hit storage.
 */
fun heal(attacker: Mob, damage: CombatDamage, attack: MagicCombatAttack<*>) {
    fun heal(dmg: CombatDamage) {
        val healAmount = floor(dmg.rawAmount * 0.25).toInt()
        if (healAmount < 1) {
            return
        }

        attacker.hitpoints.adjustLevel(healAmount)
    }

    heal(damage)
    if (attacker is Player) {
        attacker.sendMessage("You drain some of your opponent's health.")
    }
    if (attack.spellEffect.radius > 0 && attack.attacker.inMultiArea()) {
        forRadiusMobs(attack.victim, attack.spellEffect.radius) {
            val mobDamage = attack.calculateDamage(it)
            heal(mobDamage)
            attack.damageList += mobDamage
        }
    }
}

/**
 * Applies a skill-weaken effect to the primary victim and any secondary victims reached by the spell's area effect.
 *
 * @param victim The primary victim of the spell.
 * @param skill The skill id to weaken.
 * @param percent The percentage of the current level to drain.
 * @param attack The active magic attack providing spell metadata and secondary-hit storage.
 */
fun weakenAll(victim: Mob, skill: Int, percent: Double, attack: MagicCombatAttack<*>) {
    weaken(victim, victim.skill(skill), percent)
    if (attack.spellEffect.radius > 0 && attack.attacker.inMultiArea()) {
        forRadiusMobs(victim, attack.spellEffect.radius) {
            weaken(victim, victim.skill(skill), percent)
            attack.damageList += attack.calculateDamage(it)
        }
    }
}

/**
 * Applies an immobilize effect to the primary victim and any secondary victims reached by the spell's area effect.
 *
 * @param victim The primary victim of the spell.
 * @param ticks The number of ticks to immobilize affected targets for.
 * @param attack The active magic attack providing spell metadata and secondary-hit storage.
 */
fun immobilizeAll(victim: Mob, ticks: Int, attack: MagicCombatAttack<*>) {
    immobilize(victim, ticks)
    if (attack.spellEffect.radius > 0 && attack.attacker.inMultiArea()) {
        forRadiusMobs(victim, attack.spellEffect.radius) {
            immobilize(it, ticks)
            attack.damageList += attack.calculateDamage(it)
        }
    }
}

// Smoke spells.
spell(CombatSpell.SMOKE_RUSH) {
    poison(victim, 10, this)
}
spell(CombatSpell.SMOKE_BURST) {
    poison(victim, 10, this)

}
spell(CombatSpell.SMOKE_BLITZ) {
    poison(victim, 20, this)
}
spell(CombatSpell.SMOKE_BARRAGE) {
    poison(victim, 20, this)
}

// Blood spells.
spell(CombatSpell.BLOOD_RUSH) {
    heal(attacker, nextDamage, this)
}
spell(CombatSpell.BLOOD_BURST) {
    heal(attacker, nextDamage, this)
}
spell(CombatSpell.BLOOD_BLITZ) {
    heal(attacker, nextDamage, this)
}
spell(CombatSpell.BLOOD_BARRAGE) {
    heal(attacker, nextDamage, this)
}

// Shadow spells.
spell(CombatSpell.SHADOW_RUSH) {
    weakenAll(victim, SKILL_ATTACK, 0.10, this)
}
spell(CombatSpell.SHADOW_BURST) {
    weakenAll(victim, SKILL_ATTACK, 0.10, this)
}
spell(CombatSpell.SHADOW_BLITZ) {
    weakenAll(victim, SKILL_ATTACK, 0.15, this)
}
spell(CombatSpell.SHADOW_BARRAGE) {
    weakenAll(victim, SKILL_ATTACK, 0.15, this)
}

// Ice spells.
spell(CombatSpell.ICE_RUSH) {
    immobilizeAll(victim, 8, this)
}
spell(CombatSpell.ICE_BURST) {
    immobilizeAll(victim, 16, this)
}
spell(CombatSpell.ICE_BLITZ) {
    immobilizeAll(victim, 24, this)
}
spell(CombatSpell.ICE_BARRAGE) {
    immobilizeAll(victim, 32, this)
}